export default {
  results: [
    {
      popularity: 608.26,
      vote_count: 614,
      video: false,
      poster_path: '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
      id: 181812,
      adult: false,
      backdrop_path: '/dCB7d4l0mfpsISZvr6aPE2z5QF6.jpg',
      original_language: 'en',
      original_title: 'Star Wars: The Rise of Skywalker',
      genre_ids: [28, 12, 878],
      title: 'Star Wars: The Rise of Skywalker',
      vote_average: 6.8,
      overview:
        'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
      release_date: '2019-12-18'
    },
    {
      popularity: 499.933,
      vote_count: 1384,
      video: false,
      poster_path: '/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
      id: 419704,
      adult: false,
      backdrop_path: '/5BwqwxMEjeFtdknRV792Svo0K1v.jpg',
      original_language: 'en',
      original_title: 'Ad Astra',
      genre_ids: [12, 18, 9648, 878, 53],
      title: 'Ad Astra',
      vote_average: 6.1,
      overview:
        'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.',
      release_date: '2019-09-17'
    },
    {
      popularity: 358.296,
      vote_count: 6680,
      video: false,
      poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
      id: 475557,
      adult: false,
      backdrop_path: '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
      original_language: 'en',
      original_title: 'Joker',
      genre_ids: [80, 18, 53],
      title: 'Joker',
      vote_average: 8.3,
      overview:
        'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
      release_date: '2019-10-02'
    },
    {
      popularity: 242.153,
      vote_count: 402,
      video: false,
      poster_path: '/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg',
      id: 512200,
      adult: false,
      backdrop_path: '/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg',
      original_language: 'en',
      original_title: 'Jumanji: The Next Level',
      genre_ids: [28, 12, 35, 14],
      title: 'Jumanji: The Next Level',
      vote_average: 6.7,
      overview:
        'As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.',
      release_date: '2019-12-04'
    },
    {
      popularity: 179.566,
      vote_count: 579,
      video: false,
      poster_path: '/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg',
      id: 509967,
      adult: false,
      backdrop_path: '/eFw5YSorHidsajLTayo1noueIxI.jpg',
      original_language: 'en',
      original_title: '6 Underground',
      genre_ids: [28, 53],
      title: '6 Underground',
      vote_average: 6.4,
      overview:
        'After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.',
      release_date: '2019-12-13'
    },
    {
      popularity: 183.526,
      vote_count: 1150,
      video: false,
      poster_path: '/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg',
      id: 330457,
      adult: false,
      backdrop_path: '/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg',
      original_language: 'en',
      original_title: 'Frozen II',
      genre_ids: [12, 16, 10402, 10751],
      title: 'Frozen II',
      vote_average: 7,
      overview:
        'Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.',
      release_date: '2019-11-20'
    },
    {
      popularity: 131.29,
      vote_count: 3335,
      video: false,
      poster_path: '/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg',
      id: 466272,
      adult: false,
      backdrop_path: '/c6YyKddg8iVDYRRVZLDEd3m22RI.jpg',
      original_language: 'en',
      original_title: 'Once Upon a Time… in Hollywood',
      genre_ids: [35, 18, 53],
      title: 'Once Upon a Time… in Hollywood',
      vote_average: 7.5,
      overview:
        'Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…',
      release_date: '2019-07-25'
    },
    {
      popularity: 69.977,
      vote_count: 1,
      video: false,
      poster_path: '/jVr8vyatgZsPh2Po3W0IoLnMSJl.jpg',
      id: 651693,
      adult: false,
      backdrop_path: null,
      original_language: 'tl',
      original_title: 'My Bakit List',
      genre_ids: [10749],
      title: 'My Bakit List',
      vote_average: 10,
      overview:
        'Dess embarks on a soul searching journey and accidentally bumps into her ex-boyfriend who left her without any explanation.',
      release_date: '2019-12-11'
    },
    {
      popularity: 153.027,
      vote_count: 8454,
      video: false,
      poster_path: '/jpfkzbIXgKZqCZAkEkFH2VYF63s.jpg',
      id: 920,
      adult: false,
      backdrop_path: '/a1MlbLBk5Sy6YvMbSuKfwGlDVlb.jpg',
      original_language: 'en',
      original_title: 'Cars',
      genre_ids: [12, 16, 35, 10751],
      title: 'Cars',
      vote_average: 6.7,
      overview:
        'Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town\'s offbeat characters.',
      release_date: '2006-06-08'
    },
    {
      popularity: 118.319,
      vote_count: 23,
      video: false,
      poster_path: '/eU0orGizEpOli4wtN8HtfOOJDlA.jpg',
      id: 516700,
      adult: false,
      backdrop_path: '/mlaX4c2M6usnhXHG5sYJcKVXflA.jpg',
      original_language: 'id',
      original_title: 'Gundala',
      genre_ids: [28, 80, 18],
      title: 'Gundala',
      vote_average: 6.3,
      overview:
        'Sancaka has lived on the streets since his parents left him. Living a hard life, Sancaka survives by thinking about his own safety. When the condition of the city gets worse and injustice rages throughout the country, Sancaka must decide whether he continues to live to look after himself or rise to become their oppressed hero.',
      release_date: '2019-08-29'
    },
    {
      popularity: 139.93,
      vote_count: 57,
      video: false,
      poster_path: '/MBiKqTsouYqAACLYNDadsjhhC0.jpg',
      id: 486589,
      adult: false,
      backdrop_path: '/bga3i5jcejBekr2FCGJga1fYCh.jpg',
      original_language: 'en',
      original_title: 'Red Shoes and the Seven Dwarfs',
      genre_ids: [16, 10749],
      title: 'Red Shoes and the Seven Dwarfs',
      vote_average: 6.1,
      overview:
        'Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.',
      release_date: '2019-07-25'
    },
    {
      popularity: 112.899,
      vote_count: 9424,
      video: false,
      poster_path: '/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg',
      id: 181808,
      adult: false,
      backdrop_path: '/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg',
      original_language: 'en',
      original_title: 'Star Wars: The Last Jedi',
      genre_ids: [28, 12, 14, 878],
      title: 'Star Wars: The Last Jedi',
      vote_average: 7,
      overview:
        'Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.',
      release_date: '2017-12-13'
    },
    {
      popularity: 97.233,
      vote_count: 102,
      video: false,
      poster_path: '/4E2lyUGLEr3yH4q6kJxPkQUhX7n.jpg',
      id: 568012,
      adult: false,
      backdrop_path: '/iGnCzXEx0cFlUbpyAMeHwHWhPhx.jpg',
      original_language: 'ja',
      original_title: 'ワンピーススタンピード',
      genre_ids: [28, 12, 16],
      title: 'One Piece: Stampede',
      vote_average: 7.4,
      overview:
        'One Piece: Stampede is a stand-alone film that celebrates the anime\'s 20th Anniversary and takes place outside the canon of the "One Piece" TV series. Monkey D. Luffy and his Straw Hat pirate crew are invited to a massive Pirate Festival that brings many of the most iconic characters from throughout the franchise to participate in competition with the Straw Hats to find Roger\'s treasure. It also pits the Straw Hats against a new enemy named Bullet, a former member of Roger\'s crew.',
      release_date: '2019-08-09'
    },
    {
      popularity: 95.203,
      vote_count: 64,
      video: false,
      poster_path: '/84Xz2Jh60tC3ICO1CY27wc0zwgC.jpg',
      id: 461130,
      adult: false,
      backdrop_path: '/raspMdRYIj0cCF6SQH8NQ1lLLMB.jpg',
      original_language: 'en',
      original_title: 'Code 8',
      genre_ids: [28, 80, 18, 878, 53],
      title: 'Code 8',
      vote_average: 6.7,
      overview:
        'In Lincoln City, some inhabitants have extraordinary abilities. Most live below the poverty line, under the close surveillance of a heavily militarized police force. Connor, a construction worker with powers, involves with a criminal gang to help his ailing mother. (Based on the short film “Code 8,” 2016.)',
      release_date: '2019-12-06'
    },
    {
      popularity: 90.551,
      vote_count: 837,
      video: false,
      poster_path: '/kTQ3J8oTTKofAVLYnds2cHUz9KO.jpg',
      id: 522938,
      adult: false,
      backdrop_path: '/spYx9XQFODuqEVoPpvaJI1ksAVt.jpg',
      original_language: 'en',
      original_title: 'Rambo: Last Blood',
      genre_ids: [28, 18, 53],
      title: 'Rambo: Last Blood',
      vote_average: 5.9,
      overview:
        'After fighting his demons for decades, John Rambo now lives in peace on his family ranch in Arizona, but his rest is interrupted when Gabriela, the granddaughter of his housekeeper María, disappears after crossing the border into Mexico to meet her biological father. Rambo, who has become a true father figure for Gabriela over the years, undertakes a desperate and dangerous journey to find her.',
      release_date: '2019-09-19'
    },
    {
      popularity: 308.809,
      vote_count: 29,
      video: false,
      poster_path: '/jMmi8lUMNW18ugr38uaEEg6LgJK.jpg',
      id: 449924,
      adult: false,
      backdrop_path: '/ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg',
      original_language: 'cn',
      original_title: '葉問4',
      genre_ids: [28, 18, 36],
      title: 'Ip Man 4: The Finale',
      vote_average: 5.7,
      overview:
        'Ip Man 4 is an upcoming Hong Kong biographical martial arts film directed by Wilson Yip and produced by Raymond Wong. It is the fourth in the Ip Man film series based on the life of the Wing Chun grandmaster of the same name and features Donnie Yen reprising the role. The film began production in April 2018 and ended in July the same year.',
      release_date: '2019-12-20'
    },
    {
      popularity: 78.441,
      vote_count: 855,
      video: false,
      poster_path: '/pZekG6xabTmZxjmYw10wN84Hp8d.jpg',
      id: 492188,
      adult: false,
      backdrop_path: '/nwoDC0IJA47wr3znJgT1kkk64Gy.jpg',
      original_language: 'en',
      original_title: 'Marriage Story',
      genre_ids: [18],
      title: 'Marriage Story',
      vote_average: 8.1,
      overview:
        'A stage director and an actress struggle through a grueling, coast-to-coast divorce that pushes them to their personal extremes.',
      release_date: '2019-11-06'
    },
    {
      popularity: 99.353,
      id: 11,
      video: false,
      vote_count: 12470,
      vote_average: 8.2,
      title: 'Star Wars',
      release_date: '1977-05-25',
      original_language: 'en',
      original_title: 'Star Wars',
      genre_ids: [12, 28, 878],
      backdrop_path: '/4iJfYYoQzZcONB9hNzg0J0wWyPH.jpg',
      adult: false,
      overview:
        'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
      poster_path: '/btTdmkgIvOi0FFip1sPuZI2oQG6.jpg'
    },
    {
      popularity: 85.158,
      vote_count: 2539,
      video: false,
      poster_path: '/zfE0R94v1E8cuKAerbskfD3VfUt.jpg',
      id: 474350,
      adult: false,
      backdrop_path: '/8moTOzunF7p40oR5XhlDvJckOSW.jpg',
      original_language: 'en',
      original_title: 'It Chapter Two',
      genre_ids: [18, 14, 27],
      title: 'It Chapter Two',
      vote_average: 6.8,
      overview:
        '27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers\' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.',
      release_date: '2019-09-04'
    },
    {
      popularity: 83.889,
      vote_count: 1507,
      video: false,
      poster_path: '/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg',
      id: 398978,
      adult: false,
      backdrop_path: '/ww5aGS5H2tUtckxFFNOJE2790S7.jpg',
      original_language: 'en',
      original_title: 'The Irishman',
      genre_ids: [80, 18, 36],
      title: 'The Irishman',
      vote_average: 7.9,
      overview:
        'Pennsylvania, 1956. Frank Sheeran, a war veteran of Irish origin who works as a truck driver, accidentally meets mobster Russell Bufalino. Once Frank becomes his trusted man, Bufalino sends him to Chicago with the task of helping Jimmy Hoffa, a powerful union leader related to organized crime, with whom Frank will maintain a close friendship for nearly twenty years.',
      release_date: '2019-11-01'
    }
  ]
};
